# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "Lumos-${version}";
  version = "20170122-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "8229719e3df36b1e65289a85cdd4c02c7a61b9c2";

  goPackagePath = "github.com/LER0ever/Lumos";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/LER0ever/Lumos";
    sha256 = "1y0fhdjkxhyi1brkdpkf1svy67c16yf5cbnyn7ilwidpny8x2r9d";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
