# This file was generated by go2nix.
[
  {
    goPackagePath = "github.com/BurntSushi/toml";
    fetch = {
      type = "git";
      url = "https://github.com/BurntSushi/toml";
      rev = "99064174e013895bbd9b025c31100bd1d9b590ca";
      sha256 = "058qrar8rvw3wb0ci1mf1axnqq2729cvv9zmdr4ms2nn9s97yiz9";
    };
  }
  {
    goPackagePath = "github.com/Unknwon/com";
    fetch = {
      type = "git";
      url = "https://github.com/Unknwon/com";
      rev = "0db4a625e949e956314d7d1adea9bf82384cc10c";
      sha256 = "09idg84jf8wx3aazgm9s392cxjz3afq41923y19hhx7ki19s49yh";
    };
  }
  {
    goPackagePath = "github.com/aws/aws-sdk-go";
    fetch = {
      type = "git";
      url = "https://github.com/aws/aws-sdk-go";
      rev = "78568b07950e5e7948496878fe99b9436add41d4";
      sha256 = "0qi3q9qx8k055i2hlc6n8agl7nw1hzcw7aqqykla6z0hjv2hq0c3";
    };
  }
  {
    goPackagePath = "github.com/goftp/ftp";
    fetch = {
      type = "git";
      url = "https://github.com/goftp/ftp";
      rev = "5aad5a5ff76b383a09c02e3a6003e5f8463ca4ce";
      sha256 = "1hv7jghl417y8hz5m8258m80cxsqfv3ylxjfs9y7pbnqaxr1fglm";
    };
  }
  {
    goPackagePath = "github.com/gorilla/feeds";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/feeds";
      rev = "441264de03a8117ed530ae8e049d8f601a33a099";
      sha256 = "0h3hd54l9sdhvgxjspmk1sd8rhpjfiqwhjipk88fgcglyydnxns5";
    };
  }
  {
    goPackagePath = "github.com/kr/fs";
    fetch = {
      type = "git";
      url = "https://github.com/kr/fs";
      rev = "2788f0dbd16903de03cb8186e5c7d97b69ad387b";
      sha256 = "1c0fipl4rsh0v5liq1ska1dl83v3llab4k6lm8mvrx9c4dyp71ly";
    };
  }
  {
    goPackagePath = "github.com/matryer/try";
    fetch = {
      type = "git";
      url = "https://github.com/matryer/try";
      rev = "9ac251b645a2628ef89dbd2986987cc1299408ff";
      sha256 = "19fnqmpl3p54vmxgm1hmqvdc87brqx754wf3cdhq1bj04fcbb5h9";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-colorable";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-colorable";
      rev = "d898aa9fb31c91f35dd28ca75db377eff023c076";
      sha256 = "02g9amiw0mj3wc8jfx1jh5h2zrji6awg2diafsb0050zp4xr3ll3";
    };
  }
  {
    goPackagePath = "github.com/mcuadros/go-version";
    fetch = {
      type = "git";
      url = "https://github.com/mcuadros/go-version";
      rev = "257f7b9a7d87427c8d7f89469a5958d57f8abd7c";
      sha256 = "0mpbcc698503hbrlc74l3nqd6hdr0n6vybfzw10pg7qx3cpmn512";
    };
  }
  {
    goPackagePath = "github.com/pkg/errors";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/errors";
      rev = "bfd5150e4e41705ded2129ec33379de1cb90b513";
      sha256 = "084hxn4r8d4z6jhf09b93jybbvmr00rlqrv1jag05dv6qhf5kwpc";
    };
  }
  {
    goPackagePath = "github.com/pkg/sftp";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/sftp";
      rev = "1077779d4478e66c237c7be3a98ea98ff76f99ce";
      sha256 = "1y9zffm7dr6v3wyr96xza18w45yq4k82prmbrdsq610hzlmfi5az";
    };
  }
  {
    goPackagePath = "github.com/russross/blackfriday";
    fetch = {
      type = "git";
      url = "https://github.com/russross/blackfriday";
      rev = "5f33e7b7878355cd2b7e6b8eefc48a5472c69f70";
      sha256 = "0d7faqxrxvh8hwc1r8gbasgmr8x5blxvzciwspir2yafjfbqy87k";
    };
  }
  {
    goPackagePath = "github.com/shurcooL/sanitized_anchor_name";
    fetch = {
      type = "git";
      url = "https://github.com/shurcooL/sanitized_anchor_name";
      rev = "1dba4b3954bc059efc3991ec364f9f9a35f597d2";
      sha256 = "0pwap8lp79pldd95a1qi3xhlsa17m8zddpgc5jzvk6d1cjpsm6qg";
    };
  }
  {
    goPackagePath = "github.com/tdewolff/buffer";
    fetch = {
      type = "git";
      url = "https://github.com/tdewolff/buffer";
      rev = "df6253e2a2cda5aba1b5d0c59fc5bdf0a98ae192";
      sha256 = "1sa8bnkg9x1is09m3q4y2bbhr9fz1axvs8r3wrwxs599lazb6vh4";
    };
  }
  {
    goPackagePath = "github.com/tdewolff/minify";
    fetch = {
      type = "git";
      url = "https://github.com/tdewolff/minify";
      rev = "bf4ffcc476fdee34561726f5b5523dc0f87a707a";
      sha256 = "0qid8w9raxkx1bq9cn5822gj6b128w6br0xdhz0v4m1scfs8p9vs";
    };
  }
  {
    goPackagePath = "github.com/tdewolff/parse";
    fetch = {
      type = "git";
      url = "https://github.com/tdewolff/parse";
      rev = "70d04d8c1ad44f8f9e435a056f276910cb1f29bf";
      sha256 = "0cp29n712f31a17yqgyclg6jxb4a7c9bpdkph0wfr9d9ldq3m77s";
    };
  }
  {
    goPackagePath = "github.com/tdewolff/strconv";
    fetch = {
      type = "git";
      url = "https://github.com/tdewolff/strconv";
      rev = "3e8091f4417ebaaa3910da63a45ea394ebbfb0e3";
      sha256 = "00w2mryfjhz3vaqzxvbwvyhi1vgpc1s4xfv1r9hxn8hwa078q5gp";
    };
  }
  {
    goPackagePath = "github.com/tidwall/gjson";
    fetch = {
      type = "git";
      url = "https://github.com/tidwall/gjson";
      rev = "09d1c5c5bc64e094394dfe2150220d906c55ac37";
      sha256 = "1w613zj0b4jdscnbnj30yirpa1dh6mvwhz16lzg9mzwkpzlc99dq";
    };
  }
  {
    goPackagePath = "github.com/tidwall/match";
    fetch = {
      type = "git";
      url = "https://github.com/tidwall/match";
      rev = "173748da739a410c5b0b813b956f89ff94730b4c";
      sha256 = "0a4hp323gnjam3nfxfljq7d24m7rgk5vxbscjmi3ik3ph78r5avg";
    };
  }
  {
    goPackagePath = "github.com/urfave/cli";
    fetch = {
      type = "git";
      url = "https://github.com/urfave/cli";
      rev = "2526b57c56f30b50466c96c4133b1a4ad0f0191f";
      sha256 = "03vvr1wq4pw2fixxsbr1d623hwqxf93d07p8vjml6iyd6k97b15p";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "40541ccb1c6e64c947ed6f606b8a6cb4b67d7436";
      sha256 = "09x6r7ildk7gz03dynxzggz9rpjb1y8js0sqvk55v9pvsa6wrz9j";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "d379faa25cbdc04d653984913a2ceb43b0bc46d7";
      sha256 = "1mh2hkmdwyl9qvzzlsyhvq7z2y0s7p00h7inkj96fj589p9m1i2x";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "e48874b42435b4347fc52bdee0424a52abc974d7";
      sha256 = "04hsmpfnwly1bmspcq8y8b19b5gj7b0j7k1wh358jisd2d820vlg";
    };
  }
  {
    goPackagePath = "gopkg.in/fsnotify.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/fsnotify.v1";
      rev = "629574ca2a5df945712d3079857300b5e4da0236";
      sha256 = "06wfg1mmzjj04z7d0q1x2fai9k6hm957brngsaf02fa9a3qqanv3";
    };
  }
  {
    goPackagePath = "gopkg.in/inconshreveable/log15.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/inconshreveable/log15.v2";
      rev = "b105bd37f74e5d9dc7b6ad7806715c7a2b83fd3f";
      sha256 = "18rldvi60i7b3lljfrsqgcc24gdkw2pcixxydznyggaqhh96l6a8";
    };
  }
  {
    goPackagePath = "gopkg.in/ini.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/ini.v1";
      rev = "74bdc99692c3408cb103221e38675ce8fda0a718";
      sha256 = "0ad93rznilmd1hw20nlkr7ywi3sbd299mynf4db20k5yl34r3498";
    };
  }
  {
    goPackagePath = "qiniupkg.com/api.v7";
    fetch = {
      type = "git";
      url = "https://github.com/qiniu/api.v7";
      rev = "427efe34a76257db04b3b785e3b4d2fdb44cf9b9";
      sha256 = "0dg4x6yjg4xy7hd0w47fydh955ky19svbmsppbw3cp2z8xz3l4jg";
    };
  }
  {
    goPackagePath = "qiniupkg.com/x";
    fetch = {
      type = "git";
      url = "https://github.com/qiniu/x";
      rev = "f512abcf45ab4e2ba0fd4784c57b53d495997d66";
      sha256 = "1aa2hy54gip4znz8zhbpg9g0n1jz6nzdagnnvv7h9zmq9imclwyx";
    };
  }
]
